name : Demo Virtual Machine
on:
  push:
    branches: [main]
    
jobs:
  build:
    name: Virtual Machine
    runs-on: ubuntu-latest
    steps:
    - name: checkout my codes
      uses: actions/checkout@v2
    - name: Print and list out content
      run: echo Hello There!
    - name: Get remote hidden repo
      uses: actions/checkout@v2
      with:
          repository: Lowkh2/GoTrackRemoteExample
          path: remote
          token: ${{ secrets.GOTRACK }}

    - name: Show hidden File
      run: |
        cd remote
        ls   
        cat mySecret.txt
    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.19.3 # optional
 
    - name: Install dependencies for GO
      run: |
        go install github.com/franela/goblin # Adds package for Goblin testing
        go install github.com/tebeka/go2xunit # Adds package for conversion
        go test -v # Command to run go test
        go test -v | go2xunit -output report.xml # run test again and output as report.xml (to show the effect)
        ls # verify that the report is indeed created
        
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        junit_files: "report.xml"    
